<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Client\Packages\Shit\Runtime\Core\Util\SSetting.cs" Link="excelToDB\SSetting.cs" />
    <Compile Include="..\..\Client\Packages\Shit\Runtime\Game\Serialized\DBuffer.cs" Link="excelToDB\DBuffer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.MathematicsModule">
      <HintPath>..\..\..\..\..\unity\6000.7.0a5\Editor\Data\Managed\UnityEngine\UnityEngine.MathematicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
